# Generated by Django 4.0.1 on 2022-01-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longitudelatitude',
            name='email',
        ),
    ]
